README.md
=> Fix tool name in examples

src/AzureDevOpsPolicyConfigurator/Arguments/BaseSettings.cs, src/AzureDevOpsPolicyConfigurator/Arguments/ExecuterSettings.cs, src/AzureDevOpsPolicyConfigurator/Arguments/GeneratorSettings.cs, src/AzureDevOpsPolicyConfigurator/Properties/launchSettings.json
=> (GH-4) Long argument fix

src/AzureDevOpsPolicyConfigurator/Logic/WhatIfExecuter.cs
=> (GH-8) Changing will to would in WhatIf, because it's confusing.

src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuter.cs, src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuterBase.cs, src/AzureDevOpsPolicyConfigurator/Logic/WhatIfExecuter.cs
Use correct product name for Azure DevOps
=> Use correct product name for Azure DevOps

src/AzureDevOpsPolicyConfigurator/Helpers/ConnectionProvider.cs
=> Fix comment

README.md, src/AzureDevOpsPolicyConfigurator/Arguments/BaseSettings.cs, src/AzureDevOpsPolicyConfigurator/Arguments/Commands/CommandBase.cs, src/AzureDevOpsPolicyConfigurator/Arguments/Commands/ExecuteCommand.cs, src/AzureDevOpsPolicyConfigurator/Arguments/Commands/GenerateCommand.cs, src/AzureDevOpsPolicyConfigurator/Arguments/Commands/WhatIfCommand.cs, src/AzureDevOpsPolicyConfigurator/Arguments/LogLevel.cs, src/AzureDevOpsPolicyConfigurator/Helpers/ConnectionProvider.cs, src/AzureDevOpsPolicyConfigurator/Program.cs, src/AzureDevOpsPolicyConfigurator/Properties/launchSettings.json, src/AzureDevOpsPolicyConfigurator/log4net.config
=> (GH-13) Add verbose parameter

src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuterBase.cs
=> (GH-18) Handle policy as not "up to date" !IsEnabled or IsDeleted

README.md, src/AzureDevOpsPolicyConfigurator/Data/Policy.cs, src/AzureDevOpsPolicyConfigurator/Data/PolicyDefinition.cs, src/AzureDevOpsPolicyConfigurator/Helpers/PolicyExtension.cs, src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuter.cs, src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuterBase.cs, src/AzureDevOpsPolicyConfigurator/Logic/WhatIfExecuter.cs
=> (GH-16) Add specific type handling and subtype

.mergify.yml
Add mergify file to automatically delete feature branches after merge
=> Add mergify file to delete branches after merge

.gitignore, README.md, src/AzureDevOpsPolicyConfigurator.Tests/JsonMergeTests.cs, src/AzureDevOpsPolicyConfigurator/Helpers/JsonSerializer.cs, src/AzureDevOpsPolicyConfigurator/Interfaces/IJsonSerializer.cs, src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuterBase.cs
Add Json Merge
Extend Input Parameter
=> Add Json Merge

setup.cake
=> Fix dependency to build task

tools/packages.config
=> Build with Cake 0.32.1

README.md
Update readme to new Chocolatey package ID and some other fixes
=> Update readme to new Chocolatey package ID

src/AzureDevOpsPolicyConfigurator/Program.cs
=> (GH-59) Fix returning exit code

src/AzureDevOpsPolicyConfigurator/AzureDevOpsPolicyConfigurator.csproj
=> (GH-61) Bump TFS Client version to 16.148.0-preview

setup.cake
Pin build script to Cake.Recipe 1.0.0 to avoid breaking builds due to changes in Cake.Recipe
=> Pin build script to Cake.Recipe 1.0.0

README.md, src/AzureDevOpsPolicyConfigurator.Tests/MultiRepositoryDefinitionTests.cs, src/AzureDevOpsPolicyConfigurator/Data/Policy.cs, src/AzureDevOpsPolicyConfigurator/Helpers/PolicyExtension.cs, src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuterBase.cs
=> (GH-75) Add support for multiple repository definition

setup.cake
=> Enable Codecov

build.ps1, build.sh, recipe.cake
Update bootstrapper to get rid of dependency on MyGet. 
Also renames build script from `setup.cake` to `recipe.cake` to better follow other repos.
=> Update bootstrapper 

src/AzureDevOpsPolicyConfigurator/Data/Policy.cs, src/AzureDevOpsPolicyConfigurator/Helpers/PolicyExtension.cs, src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuter.cs, src/AzureDevOpsPolicyConfigurator/Logic/PolicyExecuterBase.cs, src/AzureDevOpsPolicyConfigurator/Logic/WhatIfExecuter.cs
=> Branch policies with prefix are not set corrrect

.github/workflows/release.yml
Fix release workflow step name
=> Fix release workflow step name
